FROM rasa/rasa-sdk:1.10.1

 # The Rasa SDK image runs as non-root user by default. Hence, you have to switch
 # back to the `root` user if you want to install additional dependencies
USER root

# Switch back to a non-root user
USER 1001
